### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by s3afroze** [qyzdao/ShadeSketch#4]
Hi,
Thank you for open-sourcing the project and building a demo around it! 
I was trying out the API online from https://ainize.ai/vyvydkf628/sketch but the result fails when I upload an image to test it out. 

```
TypeError: Failed to fetch
--

```
Thanks,

Shahzeb

**Comment by qyzdao** [comment]
Hi Shahzeb, I am not the developer of this API, could you please contact the developer DongCheol here? [https://github.com/vyvydkf628](url) Thanks for your likes. -Qingyuan

**Comment by hepesu** [comment]
@s3afroze We have an online demo at https://qyzdao.github.io/ShadeSketch, you can try it out in broswer.

**Comment by s3afroze** [comment]
> @s3afroze We have an online demo at https://qyzdao.github.io/ShadeSketch, you can try it out in broswer.

Hi @hepesu,
My apologies for the late response.

I checked out the demo and it is really amazing for applying the method on one picture at a time. However, I am applying it on a video (by breaking down frame images) therefore I was looking for something more scalable.

Thanks,
