### ISSUE TITLE
How to evaluate the model on my own sketch image dataset?

### ISSUE THREAD

**Issue by brian220** [qyzdao/ShadeSketch#8]
Hi,
First thanks for provide the nice implementation!
I found a link in readme [https://shinya7y.github.io/playground/shadesketch/](url) which can output a shadow image for a 
single image input. 
But know I want to convert all the images in my sketch dataset(about 10000 imgs) to shadow image,
could you give me some advice about how to achieve this?

Thanks

**Comment by hepesu** [comment]
Hi, brian220

Our repo provides a script to achieve your goal.

You can make batch evaluation with `predict.py`. The instruction is in `Evaluating` section in `README.MD`.

We also provide a [colab notebook](https://colab.research.google.com/drive/17TTdtZFaBh91yJJ1WJsVjGg0aBd-lcG2?usp=sharing) for user without development envoriment.
